config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    // $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
    //     'httpOnly' => true
    // ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    // $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Accounts', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Customer.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;


class Customer extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Table/CustomersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;


class CustomersTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('customers');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Common');
        $this->addBehavior('Timestamp');

        $this->belongsTo('Shops', [
            'foreignKey' => 'shop_id',
            'joinType' => 'INNER',
        ]);

    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->nonNegativeInteger('id')
            ->allowEmptyString('id', null, 'create');


        $validator
            ->notEmptyString('enable');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {


        return $rules;
    }
}

src/Controller/CustomersController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\Core\Configure;
use Cake\Network\Exception\NotFoundException;
use Cake\Routing\Router;


class CustomersController extends AppController
{

    /**
     * 患者一覧
     */
    public function index()
    {
        $this->set('title', __('<i class="nc-icon nc-badge"></i> 患者一覧'));

        $query = $this->Customers->find()->where(['Customers.shop_id'=>$this->Auth->user()['shop_id']]);
        $customers = $this->paginate($query);

        if ($this->request->is(['patch', 'post', 'put'])) {
            if (!$this->request->getData('id')) {
                $data = $this->Customers->newEntity();
            } else {
                $data = $this->Customers->get($this->request->getData('id'));
            }
            $data = $this->Customers->patchEntity($data, $this->request->getData());
            $data->shop_id = $this->Auth->user()['shop_id'];
            if ($this->Customers->save($data)) {
                $this->Flash->success(__('患者が登録されました。'));
                return $this->redirect(['action' => 'index']);

            } else {
                $this->log($data->errors());
                $this->Flash->error(__('患者の登録に失敗しました。'));
            }

        }

        $this->set(compact('customers'));
    }

    /**
     * 患者登録
     */
    public function edit($id = null)
    {
        $this->autoRender = false;

        $data = $this->Customers->newEntity();
        if ($id) {
            $data = $this->Customers->get($id);
            if ($data->next_date) {
                $data->next_date = $data->next_date->format('Y-m-d');
            }
            $this->log($data);
        }
        echo json_encode(compact('data'));
    }

    /**
     * 患者削除
     */
    public function delete($id = null)
    {
        $data = $this->Customers->get($id);
        $data->enable = 0;
        if ($this->Customers->save($data)) {
            $this->Flash->success(__('患者を削除しました。'));
        } else {
            $this->Flash->error(__('患者の削除に失敗しました。'));
        }

        return $this->redirect(['action' => 'index']);
    }

    /**
     * 診察券
     */
    public function view($id)
    {
        $this->viewBuilder()->setLayout('none');

        $this->set('title', __('診察券'));

        $customer = $this->Customers->get($id, [
            'contain' => ['Shops'],
        ]);

        $url = Router::url('/', true) . "customers/view/". $id;

        $this->set(compact('customer', 'url'));
    }


}

src/Template/Customers/index.ctp
<script>
    function deleteData(id) {
        Swal.fire({
            title: '',
            text: "患者を削除しますか?",
            type: 'warning',
            showCancelButton: true,
            customClass: {
            confirmButton: 'btn btn-success',
            cancelButton: 'btn btn-danger'
            },
            buttonsStyling: false,
            confirmButtonText: '削除',
            cancelButtonText: 'キャンセル'
        }).then((result) => {
            if (result.value) {
                location.href = "/customers/delete/" + id;
            }
        })
    }

    function editData(id) {
        $.ajax({
            type: "get",
            dataType: 'json',
            url: "/customers/edit/" + id,
            success : function(data){
                if (data && data.data){
                    console.log(data.data)
                    $('#id').val(data.data.id);
                    $('#no').val(data.data.no);
                    $('#name').val(data.data.name);
                    $('#kana').val(data.data.kana);
                    $('#next-date').val(data.data.next_date);

                    $('#addModal').modal()
                }
            }
        });
    }
</script>
<div class="row">
    <div class="col-xl-10 col-sm-12">
        <div class="card card-user">
            <div class="card-body">
                <button class="btn btn-outline-success btn-round" onclick="editData(0)"><span class="btn-label"><i class="fa fa-plus"></i></span>
                患者登録
                </button>
                <table class="table table-bordered table-striped text-nowrap">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col" class="actions"><?= __('診察券') ?></th>
                            <th class="text-center" scope="col"><?= $this->Paginator->sort('No.') ?></th>
                            <th class="text-center" scope="col"><?= $this->Paginator->sort('名前') ?></th>
                            <th class="text-center" scope="col" class="actions"><?= __('') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($customers as $customer): ?>
                        <tr>
                            <td class="text-center">
                                <?= $this->Html->link('発行', ['action'=>'view', $customer->id], ['escape'=>false, "class"=>"btn btn-sm  btn-behance", 'target'=>'_blank']) ?>
                            </td>
                            <td><?= h($customer->no) ?></td>
                            <td><?= h($customer->kana) ?><br/><?= h($customer->name) ?></td>
                            <td class="text-center">
                                <button class="btn btn-sm btn-icon btn-round btn-success" onclick="editData(<?= h($customer->id) ?>)">
                                    <i class="fa fa-pencil"></i>
                                </button>
                                <button class="btn btn-sm btn-icon btn-round btn-reddit" onclick="deleteData(<?= h($customer->id) ?>)">
                                    <i class="fa fa-trash-o"></i>
                                </button>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="paginator">
                    <ul class="pagination">
                        <?= $this->Paginator->first('<< ' . __('first')) ?>
                        <?= $this->Paginator->prev('< ' . __('前')) ?>
                        <?= $this->Paginator->numbers() ?>
                        <?= $this->Paginator->next(__('次') . ' >') ?>
                        <?= $this->Paginator->last(__('last') . ' >>') ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><i class="fa fa-address-card-o" aria-hidden="true"></i> 患者登録</h5>
      </div>
      <?= $this->Form->create() ?>
          <?= $this->Form->hidden('id', ["id"=>"id"]);?>

        <div class="modal-body">
            <div class="form-group">
            <label>No.</label>
                <?= $this->Form->control('no', ["class"=>"form-control", "label"=>false]);?>
            </div>
            <div class="form-group">
                <label>名前</label>
                <?= $this->Form->control('name', ["class"=>"form-control", "label"=>false]);?>
            </div>
            <div class="form-group">
                <label>カナ</label>
                <?= $this->Form->control('kana', ["class"=>"form-control", "label"=>false]);?>
            </div>
            <div class="form-group">
                <label>次回来院日</label>
                <?= $this->Form->control('next_date', ["class"=>"form-control", "label"=>false]);?>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">閉じる</button>
          <?= $this->Form->button(__('登録'), ["type"=>"submit", "class"=>"btn btn-success"]) ?>
        </div>
      <?= $this->Form->end() ?>
    </div>
  </div>
</div>

src/Template/Customers/view.ctp
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="smart card">
<link rel="apple-touch-icon" href="/img/card_192.png">
<script>
    if('serviceWorker' in navigator){
        navigator.serviceWorker.register('/serviceworker.js').then(function(){
            console.log("Service Worker Registered");
        });
    }
</script>
<div class="row">
    <div class="col-lg-6">
        <div class="card card-pricing "  style="background-color:#f4f3ef;">
            <div class="card-header" style="padding:0px;margin:0px;">
                <h4 class="card-title">
                <i class="fa fa-address-card-o"></i> 診察券<br/>
                    <?= h($customer->shop->name) ?>
                </h4>
            </div>
            <div class="card-body">
                <?=$this->QrCode->text($url);?>
                <h5 class="card-title">カルテNo.<?= h($customer->no) ?></h5>
                <ul>
                    <li><?= h($customer->kana) ?></li>
                    <li><?= h($customer->name.'様') ?></li>
                    <li><?= h("初診日：".$customer->created->format('Y年m月d日')) ?></li>
                    <li><?= $customer->next_date?h("次回来院日：".$customer->next_date->format('Y年m月d日')):"" ?></li>
                </ul>
            </div>
            <hr>
            <div class="card-footer">
                <ul class="text-warning">
                    <li><i class="fa fa-phone"></i> <?= h($customer->shop->tel) ?></li>
                    <li><?= h("〒".$customer->shop->zip.$customer->shop->address1.$customer->shop->address2) ?></li>
                </ul>
                <ul class="text-danger text-left">
                    <li><?= nl2br($customer->shop->remark) ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>